name: Emscripten

on:
  push:
      paths-ignore:
          - 'docs/**'
  pull_request:
      paths-ignore:
          - 'docs/**'


concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  emscripten:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build docker
        run: docker build -t proj-emscripten-builder scripts/ci/emscripten/

      - name: Artifacts folder
        run: mkdir -p "$PWD"/wasm_out

      - name: Run docker build
        run: |
          docker run --user $(id -u):$(id -g) --rm \
            -v "$PWD":/build/proj_src \
            -v "$PWD"/wasm_out:/build/install \
            proj-emscripten-builder

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: proj-js-wasm
          retention-days: 90
          path: wasm_out/projModule.*

      - name: Copy for tests
        run: |
          mkdir -p "$PWD"/out_node
          cp wasm_out/projModule.* out_node
          cp scripts/ci/emscripten/proj.ems.tests.js out_node

      - name: Run docker tests
        run: |
          docker run --user $(id -u):$(id -g) --rm \
            -v "$PWD"/out_node:/opt/node/tests \
            node:24-alpine \
            node /opt/node/tests/proj.ems.tests.js
